name: Render and deploy quarto files
on:
  push:
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: "Install Conda environment with Micromamba"
      uses: mamba-org/setup-micromamba@v1
      with:
        cache-env: true
        environment-file: environment.yml
        environment-name: earthaccess

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Publish to GitHub Pages (and render)
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
        EARTHACCESS_TEST_USERNAME: ${{ secrets.EDL_USERNAME }}
        EARTHACCESS_TEST_PASSWORD: ${{ secrets.EDL_PASSWORD }}
      
